[versions]
agp = "8.13.0-rc01"
bcv = "0.16.3"
build-config = "5.6.5"
core-version = "0.11.0"
coroutines = "1.10.2"
junit = "4.13.2"
junit-version = "1.3.0"
kotlin = "2.2.20"
kotlin-stdlib = "2.2.20"
kotlin-test = "2.2.20"
runner = "1.7.0"
versionCatalogUpdatePlugin = "1.0.1"
java-gradle-plugin = "1.9.0"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
kctfork-core = { module = "dev.zacsweers.kctfork:core", version.ref = "core-version" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin-stdlib" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin-test" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "bcv" }
build-config = { id = "com.github.gmazzo.buildconfig", version.ref = "build-config" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdatePlugin" }
