[versions]
agp = "8.13.0-rc01"
bcv = "0.16.3"
build-config = "5.6.5"
core = "1.7.0"
core-version = "0.11.0"
coroutines = "1.10.2"
junit = "4.13.2"
junit-version = "1.3.0"
kotlin = "2.2.20"
kotlin-stdlib = "2.2.20"
kotlin-test = "2.2.20"
runner = "1.7.0"

[libraries]
core = { group = "androidx.test", name = "core", version.ref = "core" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
junit = { module = "junit:junit", version.ref = "junit" }
kctfork-core = { module = "dev.zacsweers.kctfork:core", version.ref = "core-version" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin-stdlib" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin-test" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
runner = { group = "androidx.test", name = "runner", version.ref = "runner" }

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "bcv" }
build-config = { id = "com.github.gmazzo.buildconfig", version.ref = "build-config" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
